/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

(* hdlname = "excess3" *)
(* top =  1  *)
(* src = "/home/user/files/top_down/excess3.v:12.1-117.10" *)
module excess3(A, Y);
  (* src = "/home/user/files/top_down/excess3.v:13.20-13.21" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "/home/user/files/top_down/excess3.v:14.21-14.22" *)
  output [3:0] Y;
  wire [3:0] Y;
  (* unused_bits = "0 1" *)
  wire [2:0] if_out;
  (* unused_bits = "0" *)
  wire [1:0] if_out2;
  (* src = "/home/user/files/top_down/excess3.v:18.14-18.21" *)
  (* unused_bits = "0 1 2" *)
  wire [3:0] if_out3;
  (* unused_bits = "0" *)
  wire [1:0] if_out4;
  (* unused_bits = "0 1" *)
  wire [2:0] if_out5;
  (* src = "/home/user/files/top_down/excess3.v:21.14-21.21" *)
  wire [3:0] if_out6;
  (* src = "/home/user/files/top_down/excess3.v:22.14-22.21" *)
  wire [3:0] if_out7;
  (* hdlname = "u1 A" *)
  (* src = "/home/user/files/top_down/excess3.v:4.17-4.18" *)
  wire \u1.A ;
  (* hdlname = "u1 B" *)
  (* src = "/home/user/files/top_down/excess3.v:5.21-5.22" *)
  wire [3:0] \u1.B ;
  (* hdlname = "u1 C" *)
  (* src = "/home/user/files/top_down/excess3.v:6.22-6.23" *)
  wire [3:0] \u1.C ;
  (* hdlname = "u1 Y" *)
  (* src = "/home/user/files/top_down/excess3.v:7.20-7.21" *)
  (* unused_bits = "0 1" *)
  wire [3:0] \u1.Y ;
  (* hdlname = "u2 A" *)
  (* src = "/home/user/files/top_down/excess3.v:4.17-4.18" *)
  wire \u2.A ;
  (* hdlname = "u2 B" *)
  (* src = "/home/user/files/top_down/excess3.v:5.21-5.22" *)
  wire [3:0] \u2.B ;
  (* hdlname = "u2 C" *)
  (* src = "/home/user/files/top_down/excess3.v:6.22-6.23" *)
  wire [3:0] \u2.C ;
  (* hdlname = "u2 Y" *)
  (* src = "/home/user/files/top_down/excess3.v:7.20-7.21" *)
  (* unused_bits = "0" *)
  wire [3:0] \u2.Y ;
  (* hdlname = "u3 A" *)
  (* src = "/home/user/files/top_down/excess3.v:4.17-4.18" *)
  wire \u3.A ;
  (* hdlname = "u3 B" *)
  (* src = "/home/user/files/top_down/excess3.v:5.21-5.22" *)
  wire [3:0] \u3.B ;
  (* hdlname = "u3 C" *)
  (* src = "/home/user/files/top_down/excess3.v:6.22-6.23" *)
  wire [3:0] \u3.C ;
  (* hdlname = "u3 Y" *)
  (* src = "/home/user/files/top_down/excess3.v:7.20-7.21" *)
  (* unused_bits = "0 1 2" *)
  wire [3:0] \u3.Y ;
  (* hdlname = "u4 A" *)
  (* src = "/home/user/files/top_down/excess3.v:4.17-4.18" *)
  wire \u4.A ;
  (* hdlname = "u4 B" *)
  (* src = "/home/user/files/top_down/excess3.v:5.21-5.22" *)
  wire [3:0] \u4.B ;
  (* hdlname = "u4 C" *)
  (* src = "/home/user/files/top_down/excess3.v:6.22-6.23" *)
  wire [3:0] \u4.C ;
  (* hdlname = "u4 Y" *)
  (* src = "/home/user/files/top_down/excess3.v:7.20-7.21" *)
  (* unused_bits = "0" *)
  wire [3:0] \u4.Y ;
  (* hdlname = "u5 A" *)
  (* src = "/home/user/files/top_down/excess3.v:4.17-4.18" *)
  wire \u5.A ;
  (* hdlname = "u5 B" *)
  (* src = "/home/user/files/top_down/excess3.v:5.21-5.22" *)
  wire [3:0] \u5.B ;
  (* hdlname = "u5 C" *)
  (* src = "/home/user/files/top_down/excess3.v:6.22-6.23" *)
  wire [3:0] \u5.C ;
  (* hdlname = "u5 Y" *)
  (* src = "/home/user/files/top_down/excess3.v:7.20-7.21" *)
  (* unused_bits = "0 1" *)
  wire [3:0] \u5.Y ;
  (* hdlname = "u6 A" *)
  (* src = "/home/user/files/top_down/excess3.v:4.17-4.18" *)
  wire \u6.A ;
  (* hdlname = "u6 B" *)
  (* src = "/home/user/files/top_down/excess3.v:5.21-5.22" *)
  wire [3:0] \u6.B ;
  (* hdlname = "u6 C" *)
  (* src = "/home/user/files/top_down/excess3.v:6.22-6.23" *)
  wire [3:0] \u6.C ;
  (* hdlname = "u6 Y" *)
  (* src = "/home/user/files/top_down/excess3.v:7.20-7.21" *)
  wire [3:0] \u6.Y ;
  (* hdlname = "u7 A" *)
  (* src = "/home/user/files/top_down/excess3.v:4.17-4.18" *)
  wire \u7.A ;
  (* hdlname = "u7 B" *)
  (* src = "/home/user/files/top_down/excess3.v:5.21-5.22" *)
  wire [3:0] \u7.B ;
  (* hdlname = "u7 C" *)
  (* src = "/home/user/files/top_down/excess3.v:6.22-6.23" *)
  wire [3:0] \u7.C ;
  (* hdlname = "u7 Y" *)
  (* src = "/home/user/files/top_down/excess3.v:7.20-7.21" *)
  wire [3:0] \u7.Y ;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h1314)
  ) Y_SB_LUT4_O (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h4642)
  ) Y_SB_LUT4_O_1 (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0057)
  ) Y_SB_LUT4_O_2 (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h5007)
  ) Y_SB_LUT4_O_3 (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[1])
  );
  assign if_out[2:1] = { A[0], if_out[0] };
  assign if_out2 = { A[0], if_out[0] };
  assign if_out3 = { A[0], if_out[0], if_out[0], if_out[0] };
  assign if_out4 = { A[0], if_out[0] };
  assign if_out5 = { A[0], if_out[0], if_out[0] };
  assign if_out6 = 4'h0;
  assign if_out7 = 4'h0;
  assign \u1.A  = A[0];
  assign \u1.B  = 4'h4;
  assign \u1.C  = 4'h3;
  assign \u1.Y  = { 1'h0, A[0], if_out[0], if_out[0] };
  assign \u2.A  = A[0];
  assign \u2.B  = 4'h6;
  assign \u2.C  = 4'h5;
  assign \u2.Y  = { 2'h1, A[0], if_out[0] };
  assign \u3.A  = A[0];
  assign \u3.B  = 4'h8;
  assign \u3.C  = 4'h7;
  assign \u3.Y  = { A[0], if_out[0], if_out[0], if_out[0] };
  assign \u4.A  = A[0];
  assign \u4.B  = 4'ha;
  assign \u4.C  = 4'h9;
  assign \u4.Y  = { 2'h2, A[0], if_out[0] };
  assign \u5.A  = A[0];
  assign \u5.B  = 4'hc;
  assign \u5.C  = 4'hb;
  assign \u5.Y  = { 1'h1, A[0], if_out[0], if_out[0] };
  assign \u6.A  = A[0];
  assign \u6.B  = 4'h0;
  assign \u6.C  = 4'h0;
  assign \u6.Y  = 4'h0;
  assign \u7.A  = A[0];
  assign \u7.B  = 4'h0;
  assign \u7.C  = 4'h0;
  assign \u7.Y  = 4'h0;
endmodule
