#!/bin/bash

#sudo rm -rf $HOME/Pictures/*
rm *.il
rm *.txt
rm *.png
rm *.dot
rm *.pid
rm *.new
shopt -s nullglob
END=1000
for folder in $HOME/files/*/
do 	
	type=$(basename "$folder")
	#echo $type
	for filepath in "$folder"*
	do	
		safe_name=$(printf '%s\n' "${filepath##*/}" | sed 's/[&/\]/\\&/g')
		safe_name=${safe_name%.*}
		#echo $safe_name
		pic="${safe_name}_${type}"
		
		python3 $HOME/codes/cake.py "$safe_name" "$type" "1"
		$HOME/yosys/./yosys -p "synth_ice40 -top $safe_name" -g -d -l "log_${pic}.txt" $filepath
		$HOME/yosys/./yosys -p "synth_ice40 -top $safe_name" -X -g -d -l "debug_${pic}.txt" $filepath
		$HOME/yosys_mod/./yosys -Q -g -l "show_${pic}.txt" -c ~/codes/setup_show_nooptions.tcl $filepath
		mkdir -p $HOME/Pictures/${type}/${pic}
		mkdir -p $HOME/Pictures/${type}/${pic}/dumps
		mv *.png *.txt *.v  $HOME/Pictures/${type}/${pic}
		mv *.il $HOME/Pictures/$type/${pic}/dumps
		rm -f *.dot
		
		for fold in $HOME/Pictures/${type}/$pic*
		do
			python3 $HOME/codes/duplicates.py $HOME/Pictures/${type}/$pic
		done
		for fold in $HOME/Pictures/${type}/$pic/dumps*
		do
			python3 $HOME/codes/duplicates.py $HOME/Pictures/${type}/$pic/dumps
		done
	done
done
shopt -s nullglob
