/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

(* hdlname = "BCD2421_to_bin" *)
(* top =  1  *)
(* src = "/home/user/files/top_down/BCD2421_to_bin.v:281.1-291.10" *)
module BCD2421_to_bin(A, Y);
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:282.20-282.21" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:283.22-283.23" *)
  output [3:0] Y;
  wire [3:0] Y;
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:285.15-285.18" *)
  wire [3:0] out;
  (* hdlname = "u15 A" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:4.22-4.23" *)
  wire [3:0] \u15.A ;
  (* hdlname = "u15 Y" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:5.21-5.22" *)
  wire [3:0] \u15.Y ;
  (* hdlname = "u15 case2_out1" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:7.15-7.25" *)
  (* unused_bits = "0 1 2" *)
  wire [3:0] \u15.case2_out1 ;
  (* hdlname = "u15 u1 A" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:30.22-30.23" *)
  wire [3:0] \u15.u1.A ;
  (* hdlname = "u15 u1 Y" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:31.21-31.22" *)
  (* unused_bits = "0 1 2" *)
  wire [3:0] \u15.u1.Y ;
  (* hdlname = "u15 u1 case2_out3" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:33.15-33.25" *)
  wire [3:0] \u15.u1.case2_out3 ;
  (* hdlname = "u15 u1 case2_out4" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:34.15-34.25" *)
  (* unused_bits = "2" *)
  wire [3:0] \u15.u1.case2_out4 ;
  (* hdlname = "u15 u1 u3 A" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:82.23-82.24" *)
  wire [3:0] \u15.u1.u3.A ;
  (* hdlname = "u15 u1 u3 Y" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:83.21-83.22" *)
  wire [3:0] \u15.u1.u3.Y ;
  (* hdlname = "u15 u1 u3 case1_out1" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:85.15-85.25" *)
  wire [3:0] \u15.u1.u3.case1_out1 ;
  (* hdlname = "u15 u1 u3 case1_out2" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:86.15-86.25" *)
  wire [3:0] \u15.u1.u3.case1_out2 ;
  (* hdlname = "u15 u1 u3 u7 A" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:186.23-186.24" *)
  wire [3:0] \u15.u1.u3.u7.A ;
  (* hdlname = "u15 u1 u3 u7 Y" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:187.21-187.22" *)
  wire [3:0] \u15.u1.u3.u7.Y ;
  (* hdlname = "u15 u1 u3 u8 A" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:198.23-198.24" *)
  wire [3:0] \u15.u1.u3.u8.A ;
  (* hdlname = "u15 u1 u3 u8 Y" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:199.21-199.22" *)
  wire [3:0] \u15.u1.u3.u8.Y ;
  (* hdlname = "u15 u1 u4 A" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:108.23-108.24" *)
  wire [3:0] \u15.u1.u4.A ;
  (* hdlname = "u15 u1 u4 Y" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:109.21-109.22" *)
  (* unused_bits = "2" *)
  wire [3:0] \u15.u1.u4.Y ;
  (* hdlname = "u15 u1 u4 case1_out3" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:111.15-111.25" *)
  (* unused_bits = "2" *)
  wire [3:0] \u15.u1.u4.case1_out3 ;
  (* hdlname = "u15 u1 u4 case1_out4" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:112.15-112.25" *)
  wire [3:0] \u15.u1.u4.case1_out4 ;
  (* hdlname = "u15 u1 u4 u10 A" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:222.23-222.24" *)
  wire [3:0] \u15.u1.u4.u10.A ;
  (* hdlname = "u15 u1 u4 u10 Y" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:223.21-223.22" *)
  wire [3:0] \u15.u1.u4.u10.Y ;
  (* hdlname = "u15 u1 u4 u9 A" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:210.23-210.24" *)
  wire [3:0] \u15.u1.u4.u9.A ;
  (* hdlname = "u15 u1 u4 u9 Y" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:211.21-211.22" *)
  (* unused_bits = "2" *)
  wire [3:0] \u15.u1.u4.u9.Y ;
  (* hdlname = "u15 u2 A" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:56.23-56.24" *)
  wire [3:0] \u15.u2.A ;
  (* hdlname = "u15 u2 case2_out5" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:59.15-59.25" *)
  (* unused_bits = "0 2" *)
  wire [3:0] \u15.u2.case2_out5 ;
  (* hdlname = "u15 u2 case2_out6" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:60.15-60.25" *)
  (* unused_bits = "1 2" *)
  wire [3:0] \u15.u2.case2_out6 ;
  (* hdlname = "u15 u2 u5 A" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:134.23-134.24" *)
  wire [3:0] \u15.u2.u5.A ;
  (* hdlname = "u15 u2 u5 Y" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:135.21-135.22" *)
  (* unused_bits = "0 2" *)
  wire [3:0] \u15.u2.u5.Y ;
  (* hdlname = "u15 u2 u5 case1_out5" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:137.15-137.25" *)
  wire [3:0] \u15.u2.u5.case1_out5 ;
  (* hdlname = "u15 u2 u5 case1_out6" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:138.15-138.25" *)
  wire [3:0] \u15.u2.u5.case1_out6 ;
  (* hdlname = "u15 u2 u5 u11 A" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:234.23-234.24" *)
  wire [3:0] \u15.u2.u5.u11.A ;
  (* hdlname = "u15 u2 u5 u11 Y" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:235.21-235.22" *)
  wire [3:0] \u15.u2.u5.u11.Y ;
  (* hdlname = "u15 u2 u5 u12 A" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:246.23-246.24" *)
  wire [3:0] \u15.u2.u5.u12.A ;
  (* hdlname = "u15 u2 u5 u12 Y" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:247.21-247.22" *)
  wire [3:0] \u15.u2.u5.u12.Y ;
  (* hdlname = "u15 u2 u6 A" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:160.23-160.24" *)
  wire [3:0] \u15.u2.u6.A ;
  (* hdlname = "u15 u2 u6 Y" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:161.21-161.22" *)
  (* unused_bits = "1 2" *)
  wire [3:0] \u15.u2.u6.Y ;
  (* hdlname = "u15 u2 u6 case1_out7" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:163.15-163.25" *)
  wire [3:0] \u15.u2.u6.case1_out7 ;
  (* hdlname = "u15 u2 u6 case1_out8" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:164.15-164.25" *)
  wire [3:0] \u15.u2.u6.case1_out8 ;
  (* hdlname = "u15 u2 u6 u13 A" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:258.23-258.24" *)
  wire [3:0] \u15.u2.u6.u13.A ;
  (* hdlname = "u15 u2 u6 u13 Y" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:259.21-259.22" *)
  wire [3:0] \u15.u2.u6.u13.Y ;
  (* hdlname = "u15 u2 u6 u14 A" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:270.23-270.24" *)
  wire [3:0] \u15.u2.u6.u14.A ;
  (* hdlname = "u15 u2 u6 u14 Y" *)
  (* src = "/home/user/files/top_down/BCD2421_to_bin.v:271.21-271.22" *)
  wire [3:0] \u15.u2.u6.u14.Y ;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h03c0)
  ) Y_SB_LUT4_O (
    .I0(1'h0),
    .I1(A[3]),
    .I2(A[2]),
    .I3(A[1]),
    .O(Y[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hb900)
  ) Y_SB_LUT4_O_1 (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h280c)
  ) Y_SB_LUT4_O_2 (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hc000)
  ) Y_SB_LUT4_O_3 (
    .I0(1'h0),
    .I1(A[3]),
    .I2(A[2]),
    .I3(A[1]),
    .O(Y[3])
  );
  assign out = Y;
  assign \u15.A  = A;
  assign \u15.Y  = Y;
  assign \u15.case2_out1 [3] = 1'h0;
  assign \u15.u1.A  = A;
  assign \u15.u1.Y  = { 1'h0, \u15.case2_out1 [2:0] };
  assign \u15.u1.case2_out3  = { 2'h0, A[1:0] };
  assign { \u15.u1.case2_out4 [3], \u15.u1.case2_out4 [1:0] } = 3'h0;
  assign \u15.u1.u3.A  = A;
  assign \u15.u1.u3.Y  = { 2'h0, A[1:0] };
  assign \u15.u1.u3.case1_out1  = { 3'h0, A[0] };
  assign \u15.u1.u3.case1_out2  = { 3'h1, A[0] };
  assign \u15.u1.u3.u7.A  = A;
  assign \u15.u1.u3.u7.Y  = { 3'h0, A[0] };
  assign \u15.u1.u3.u8.A  = A;
  assign \u15.u1.u3.u8.Y  = { 3'h1, A[0] };
  assign \u15.u1.u4.A  = A;
  assign \u15.u1.u4.Y  = { 1'h0, \u15.u1.case2_out4 [2], 2'h0 };
  assign { \u15.u1.u4.case1_out3 [3], \u15.u1.u4.case1_out3 [1:0] } = 3'h0;
  assign \u15.u1.u4.case1_out4  = 4'h0;
  assign \u15.u1.u4.u10.A  = A;
  assign \u15.u1.u4.u10.Y  = 4'h0;
  assign \u15.u1.u4.u9.A  = A;
  assign \u15.u1.u4.u9.Y  = { 1'h0, \u15.u1.u4.case1_out3 [2], 2'h0 };
  assign \u15.u2.A  = A;
  assign \u15.u2.case2_out5 [3:1] = { 1'h0, \u15.u2.case2_out5 [0], 1'h0 };
  assign { \u15.u2.case2_out6 [3:2], \u15.u2.case2_out6 [0] } = { A[1], \u15.u2.case2_out6 [1], A[0] };
  assign \u15.u2.u5.A  = A;
  assign \u15.u2.u5.Y  = { 1'h0, \u15.u2.case2_out5 [0], 1'h0, \u15.u2.case2_out5 [0] };
  assign \u15.u2.u5.case1_out5  = 4'h0;
  assign \u15.u2.u5.case1_out6  = { 1'h0, A[0], 1'h0, A[0] };
  assign \u15.u2.u5.u11.A  = A;
  assign \u15.u2.u5.u11.Y  = 4'h0;
  assign \u15.u2.u5.u12.A  = A;
  assign \u15.u2.u5.u12.Y  = { 1'h0, A[0], 1'h0, A[0] };
  assign \u15.u2.u6.A  = A;
  assign \u15.u2.u6.Y  = { A[1], \u15.u2.case2_out6 [1], \u15.u2.case2_out6 [1], A[0] };
  assign \u15.u2.u6.case1_out7  = { 3'h3, A[0] };
  assign \u15.u2.u6.case1_out8  = { 3'h4, A[0] };
  assign \u15.u2.u6.u13.A  = A;
  assign \u15.u2.u6.u13.Y  = { 3'h3, A[0] };
  assign \u15.u2.u6.u14.A  = A;
  assign \u15.u2.u6.u14.Y  = { 3'h4, A[0] };
endmodule
