/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

(* hdlname = "gray_to_bin" *)
(* top =  1  *)
(* src = "/home/user/files/top_down/gray_to_bin.v:34.1-145.10" *)
module gray_to_bin(A, Y);
  (* src = "/home/user/files/top_down/gray_to_bin.v:35.21-35.22" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "/home/user/files/top_down/gray_to_bin.v:36.22-36.23" *)
  output [3:0] Y;
  wire [3:0] Y;
  (* hdlname = "and2 B" *)
  (* src = "/home/user/files/top_down/gray_to_bin.v:12.17-12.18" *)
  wire \and2.B ;
  (* hdlname = "and3 B" *)
  (* src = "/home/user/files/top_down/gray_to_bin.v:12.17-12.18" *)
  wire \and3.B ;
  (* hdlname = "and5 A" *)
  (* src = "/home/user/files/top_down/gray_to_bin.v:11.17-11.18" *)
  wire \and5.A ;
  (* hdlname = "and5 B" *)
  (* src = "/home/user/files/top_down/gray_to_bin.v:12.17-12.18" *)
  wire \and5.B ;
  (* hdlname = "and6 B" *)
  (* src = "/home/user/files/top_down/gray_to_bin.v:12.17-12.18" *)
  wire \and6.B ;
  (* hdlname = "and7 A" *)
  (* src = "/home/user/files/top_down/gray_to_bin.v:11.17-11.18" *)
  wire \and7.A ;
  (* hdlname = "not1 A" *)
  (* src = "/home/user/files/top_down/gray_to_bin.v:4.17-4.18" *)
  wire \not1.A ;
  (* hdlname = "not2 A" *)
  (* src = "/home/user/files/top_down/gray_to_bin.v:4.17-4.18" *)
  wire \not2.A ;
  (* hdlname = "not3 A" *)
  (* src = "/home/user/files/top_down/gray_to_bin.v:4.17-4.18" *)
  wire \not3.A ;
  (* hdlname = "or3 Y" *)
  (* src = "/home/user/files/top_down/gray_to_bin.v:21.17-21.18" *)
  wire \or3.Y ;
  (* force_downto = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:6.21-6.22" *)
  wire [1:0] \or3.Y_SB_LUT4_O_I3 ;
  (* src = "/home/user/files/top_down/gray_to_bin.v:40.22-40.26" *)
  wire or_3;
  (* hdlname = "xor1 A" *)
  (* src = "/home/user/files/top_down/gray_to_bin.v:27.17-27.18" *)
  wire \xor1.A ;
  (* hdlname = "xor1 B" *)
  (* src = "/home/user/files/top_down/gray_to_bin.v:28.17-28.18" *)
  wire \xor1.B ;
  (* hdlname = "xor1 Y" *)
  (* src = "/home/user/files/top_down/gray_to_bin.v:29.17-29.18" *)
  wire \xor1.Y ;
  (* hdlname = "xor2 A" *)
  (* src = "/home/user/files/top_down/gray_to_bin.v:27.17-27.18" *)
  wire \xor2.A ;
  (* hdlname = "xor2 B" *)
  (* src = "/home/user/files/top_down/gray_to_bin.v:28.17-28.18" *)
  wire \xor2.B ;
  (* hdlname = "xor3 A" *)
  (* src = "/home/user/files/top_down/gray_to_bin.v:27.17-27.18" *)
  wire \xor3.A ;
  (* hdlname = "xor3 Y" *)
  (* src = "/home/user/files/top_down/gray_to_bin.v:29.17-29.18" *)
  wire \xor3.Y ;
  (* src = "/home/user/files/top_down/gray_to_bin.v:41.10-41.17" *)
  wire xor_out;
  (* src = "/home/user/files/top_down/gray_to_bin.v:41.29-41.37" *)
  wire xor_out3;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf00f)
  ) \or3.Y_SB_LUT4_O  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(A[1]),
    .I3(\or3.Y_SB_LUT4_O_I3 [1]),
    .O(\or3.Y )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf00f)
  ) \or3.Y_SB_LUT4_O_I3_SB_LUT4_O  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(A[3]),
    .I3(A[2]),
    .O(\or3.Y_SB_LUT4_O_I3 [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0ff0)
  ) \xor1.Y_SB_LUT4_O  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(A[3]),
    .I3(A[2]),
    .O(\xor1.Y )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hc33c)
  ) \xor3.Y_SB_LUT4_O  (
    .I0(1'h0),
    .I1(A[1]),
    .I2(A[0]),
    .I3(\xor1.Y ),
    .O(\xor3.Y )
  );
  assign \not1.A  = A[1];
  assign Y = { A[3], \xor1.Y , \or3.Y , \xor3.Y  };
  assign \and3.B  = A[2];
  assign \and7.A  = A[3];
  assign \and6.B  = A[1];
  assign \not3.A  = A[3];
  assign \and2.B  = A[1];
  assign \and5.B  = A[2];
  assign or_3 = \or3.Y ;
  assign \xor1.A  = A[3];
  assign \xor1.B  = A[2];
  assign \xor2.A  = A[1];
  assign \xor2.B  = A[0];
  assign \or3.Y_SB_LUT4_O_I3 [0] = A[1];
  assign \xor3.A  = \xor1.Y ;
  assign \and5.A  = A[3];
  assign xor_out = \xor1.Y ;
  assign \not2.A  = A[2];
  assign xor_out3 = \xor3.Y ;
endmodule
