/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

(* hdlname = "XS3_Gray_to_bin" *)
(* top =  1  *)
(* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:92.1-241.10" *)
module XS3_Gray_to_bin(A, B, C, Y);
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:94.24-94.25" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:95.25-95.26" *)
  input [3:0] B;
  wire [3:0] B;
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:96.25-96.26" *)
  input [3:0] C;
  wire [3:0] C;
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:97.25-97.26" *)
  output [3:0] Y;
  wire [3:0] Y;
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:99.15-99.21" *)
  wire [3:0] if_out;
  (* unused_bits = "2" *)
  wire [2:0] if_out2;
  (* unused_bits = "0" *)
  wire [1:0] if_out3;
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:102.15-102.22" *)
  (* unused_bits = "3" *)
  wire [3:0] if_out4;
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:103.15-103.25" *)
  (* unused_bits = "0" *)
  wire [3:0] switch_out;
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:104.15-104.26" *)
  wire [3:0] switch_out2;
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:105.15-105.26" *)
  wire [3:0] switch_out3;
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:106.14-106.25" *)
  (* unused_bits = "0 3" *)
  wire [3:0] switch_out4;
  (* hdlname = "u1 A" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:4.17-4.18" *)
  wire \u1.A ;
  (* hdlname = "u1 B" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:5.27-5.28" *)
  wire [3:0] \u1.B ;
  (* hdlname = "u1 C" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:6.28-6.29" *)
  wire [3:0] \u1.C ;
  (* hdlname = "u1 G" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:9.28-9.29" *)
  wire [3:1] \u1.G ;
  (* hdlname = "u1 Y" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:8.28-8.29" *)
  wire [3:0] \u1.Y ;
  (* hdlname = "u10 A" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:16.17-16.18" *)
  wire \u10.A ;
  (* hdlname = "u10 B" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:17.27-17.28" *)
  wire [2:0] \u10.B ;
  (* hdlname = "u10 C" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:18.28-18.29" *)
  wire [2:0] \u10.C ;
  (* hdlname = "u10 Y" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:19.27-19.28" *)
  wire [2:0] \u10.Y ;
  (* hdlname = "u11 A" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:16.17-16.18" *)
  wire \u11.A ;
  (* hdlname = "u11 B" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:17.27-17.28" *)
  wire [3:0] \u11.B ;
  (* hdlname = "u11 C" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:18.28-18.29" *)
  wire [3:0] \u11.C ;
  (* hdlname = "u11 Y" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:19.27-19.28" *)
  (* unused_bits = "0 3" *)
  wire [3:0] \u11.Y ;
  (* hdlname = "u12 Y" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:43.21-43.22" *)
  wire [3:0] \u12.Y ;
  (* hdlname = "u13 B" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:50.21-50.22" *)
  wire [3:0] \u13.B ;
  (* hdlname = "u13 Y" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:52.22-52.23" *)
  wire [3:0] \u13.Y ;
  (* hdlname = "u14 Y" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:61.21-61.22" *)
  wire [3:0] \u14.Y ;
  (* hdlname = "u15 Y" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:74.21-74.22" *)
  wire [3:0] \u15.Y ;
  (* hdlname = "u16 A" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:84.17-84.18" *)
  wire \u16.A ;
  (* hdlname = "u16 B" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:85.21-85.22" *)
  wire [3:0] \u16.B ;
  (* hdlname = "u16 Y" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:87.22-87.23" *)
  wire [3:0] \u16.Y ;
  (* hdlname = "u2 A" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:4.17-4.18" *)
  wire \u2.A ;
  (* hdlname = "u2 B" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:5.27-5.28" *)
  wire [3:0] \u2.B ;
  (* hdlname = "u2 C" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:6.28-6.29" *)
  wire [3:0] \u2.C ;
  (* hdlname = "u2 G" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:9.28-9.29" *)
  wire [3:1] \u2.G ;
  (* hdlname = "u2 Y" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:8.28-8.29" *)
  wire [3:0] \u2.Y ;
  (* hdlname = "u3 A" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:4.17-4.18" *)
  wire \u3.A ;
  (* hdlname = "u3 B" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:5.27-5.28" *)
  wire [3:0] \u3.B ;
  (* hdlname = "u3 C" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:6.28-6.29" *)
  wire [3:0] \u3.C ;
  (* hdlname = "u3 G" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:9.28-9.29" *)
  wire [3:1] \u3.G ;
  (* hdlname = "u3 Y" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:8.28-8.29" *)
  (* unused_bits = "2" *)
  wire [3:0] \u3.Y ;
  (* hdlname = "u4 A" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:4.17-4.18" *)
  wire \u4.A ;
  (* hdlname = "u4 B" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:5.27-5.28" *)
  wire [3:0] \u4.B ;
  (* hdlname = "u4 C" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:6.28-6.29" *)
  wire [3:0] \u4.C ;
  (* hdlname = "u4 G" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:9.28-9.29" *)
  wire [3:1] \u4.G ;
  (* hdlname = "u4 Y" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:8.28-8.29" *)
  (* unused_bits = "0" *)
  wire [3:0] \u4.Y ;
  (* hdlname = "u5 A" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:4.17-4.18" *)
  wire \u5.A ;
  (* hdlname = "u5 B" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:5.27-5.28" *)
  wire [7:0] \u5.B ;
  (* hdlname = "u5 C" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:6.28-6.29" *)
  wire [7:0] \u5.C ;
  (* hdlname = "u5 G" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:9.28-9.29" *)
  wire [7:1] \u5.G ;
  (* hdlname = "u5 Y" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:8.28-8.29" *)
  (* unused_bits = "3" *)
  wire [7:0] \u5.Y ;
  (* hdlname = "u7 A" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:16.17-16.18" *)
  wire \u7.A ;
  (* hdlname = "u7 B" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:17.27-17.28" *)
  wire [2:0] \u7.B ;
  (* hdlname = "u7 C" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:18.28-18.29" *)
  wire [2:0] \u7.C ;
  (* hdlname = "u7 Y" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:19.27-19.28" *)
  (* unused_bits = "0" *)
  wire [2:0] \u7.Y ;
  (* hdlname = "u8 A" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:16.17-16.18" *)
  wire \u8.A ;
  (* hdlname = "u8 B" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:17.27-17.28" *)
  wire [2:0] \u8.B ;
  (* hdlname = "u8 C" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:18.28-18.29" *)
  wire [2:0] \u8.C ;
  (* hdlname = "u8 Y" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:19.27-19.28" *)
  wire [2:0] \u8.Y ;
  (* hdlname = "u9 A" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:16.17-16.18" *)
  wire \u9.A ;
  (* hdlname = "u9 B" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:17.27-17.28" *)
  wire [2:0] \u9.B ;
  (* hdlname = "u9 C" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:18.28-18.29" *)
  wire [2:0] \u9.C ;
  (* hdlname = "u9 Y" *)
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:19.27-19.28" *)
  wire [2:0] \u9.Y ;
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:107.15-107.22" *)
  wire [3:0] useless;
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:108.15-108.23" *)
  wire [3:0] useless2;
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:109.15-109.23" *)
  wire [3:0] useless3;
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:110.15-110.23" *)
  wire [3:0] useless4;
  (* src = "/home/user/files/top_down/XS3_Gray_to_bin.v:111.15-111.23" *)
  wire [3:0] useless5;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h8468)
  ) Y_SB_LUT4_O (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) Y_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(A[2]),
    .I3(A[0]),
    .O(Y[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h00c0)
  ) Y_SB_LUT4_O_2 (
    .I0(1'h0),
    .I1(A[3]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h880c)
  ) Y_SB_LUT4_O_3 (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[2])
  );
  assign if_out = 4'h0;
  assign if_out2[1:0] = { A[0], A[0] };
  assign if_out3 = { A[0], if_out2[2] };
  assign if_out4 = { if_out2[2], A[0], A[0], A[0] };
  assign switch_out = { 2'h0, A[0], if_out2[2] };
  assign switch_out2 = 4'b0xxx;
  assign switch_out3 = 4'h0;
  assign switch_out4 = { if_out2[2], 2'h0, if_out2[2] };
  assign \u1.A  = A[0];
  assign \u1.B  = 4'h0;
  assign \u1.C  = 4'h0;
  assign \u1.G  = 3'h0;
  assign \u1.Y  = 4'h0;
  assign \u10.A  = A[0];
  assign \u10.B  = 3'h0;
  assign \u10.C  = 3'h1;
  assign \u10.Y  = 3'h0;
  assign \u11.A  = A[0];
  assign \u11.B  = 4'h9;
  assign \u11.C  = 4'h0;
  assign \u11.Y  = { if_out2[2], 2'h0, if_out2[2] };
  assign \u12.Y  = 4'h4;
  assign \u13.B  = 4'b000x;
  assign \u13.Y  = 4'h4;
  assign \u14.Y  = 4'h4;
  assign \u15.Y  = 4'h4;
  assign \u16.A  = 1'h1;
  assign \u16.B  = 4'hf;
  assign \u16.Y  = 4'he;
  assign \u2.A  = A[0];
  assign \u2.B  = 4'h0;
  assign \u2.C  = 4'h0;
  assign \u2.G  = 3'h0;
  assign \u2.Y  = 4'h0;
  assign \u3.A  = A[0];
  assign \u3.B  = 4'h3;
  assign \u3.C  = 4'h4;
  assign \u3.G  = 3'h0;
  assign \u3.Y  = { 1'h0, if_out2[2], A[0], A[0] };
  assign \u4.A  = A[0];
  assign \u4.B  = 4'h6;
  assign \u4.C  = 4'h5;
  assign \u4.G  = 3'h0;
  assign \u4.Y  = { 2'h1, A[0], if_out2[2] };
  assign \u5.A  = A[0];
  assign \u5.B  = 8'h07;
  assign \u5.C  = 8'h08;
  assign \u5.G  = 7'h00;
  assign \u5.Y  = { 4'hx, if_out2[2], A[0], A[0], A[0] };
  assign \u7.A  = A[0];
  assign \u7.B  = 3'h1;
  assign \u7.C  = 3'h2;
  assign \u7.Y  = { 1'h0, A[0], if_out2[2] };
  assign \u8.A  = A[0];
  assign \u8.B  = 3'h6;
  assign \u8.C  = 3'h2;
  assign \u8.Y  = 3'hx;
  assign \u9.A  = A[0];
  assign \u9.B  = 3'h0;
  assign \u9.C  = 3'h0;
  assign \u9.Y  = 3'h0;
  assign useless = 4'h4;
  assign useless2 = 4'h4;
  assign useless3 = 4'h4;
  assign useless4 = 4'h4;
  assign useless5 = 4'he;
endmodule
