/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

(* hdlname = "BCD2421_to_bin" *)
(* top =  1  *)
(* src = "/home/user/files/switch_(whole)/BCD2421_to_bin.v:3.1-36.10" *)
module BCD2421_to_bin(A, Y);
  (* src = "/home/user/files/switch_(whole)/BCD2421_to_bin.v:3.39-3.40" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "/home/user/files/switch_(whole)/BCD2421_to_bin.v:3.58-3.59" *)
  output [3:0] Y;
  wire [3:0] Y;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h03c0)
  ) Y_SB_LUT4_O (
    .I0(1'h0),
    .I1(A[3]),
    .I2(A[2]),
    .I3(A[1]),
    .O(Y[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hb900)
  ) Y_SB_LUT4_O_1 (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h280c)
  ) Y_SB_LUT4_O_2 (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hc000)
  ) Y_SB_LUT4_O_3 (
    .I0(1'h0),
    .I1(A[3]),
    .I2(A[2]),
    .I3(A[1]),
    .O(Y[3])
  );
endmodule
