/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

(* hdlname = "susskind_to_bin" *)
(* top =  1  *)
(* src = "/home/user/files/top_down/susskind_to_bin.v:309.1-319.10" *)
module susskind_to_bin(A, Y);
  (* src = "/home/user/files/top_down/susskind_to_bin.v:310.20-310.21" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "/home/user/files/top_down/susskind_to_bin.v:311.22-311.23" *)
  output [3:0] Y;
  wire [3:0] Y;
  (* src = "/home/user/files/top_down/susskind_to_bin.v:313.15-313.18" *)
  wire [3:0] out;
  (* hdlname = "u24 A" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:4.22-4.23" *)
  wire [3:0] \u24.A ;
  (* hdlname = "u24 Y" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:5.21-5.22" *)
  wire [3:0] \u24.Y ;
  (* hdlname = "u24 if_out1" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:7.15-7.22" *)
  wire [3:0] \u24.if_out1 ;
  (* hdlname = "u24 if_out2" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:8.15-8.22" *)
  wire [3:0] \u24.if_out2 ;
  (* hdlname = "u24 u1 Y" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:214.22-214.23" *)
  wire [3:0] \u24.u1.Y ;
  (* hdlname = "u24 u2 Y" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:220.22-220.23" *)
  wire [3:0] \u24.u2.Y ;
  (* hdlname = "u24 u3 A" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:31.22-31.23" *)
  wire [3:0] \u24.u3.A ;
  (* hdlname = "u24 u3 if_out4" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:34.15-34.22" *)
  wire [3:0] \u24.u3.if_out4 ;
  (* hdlname = "u24 u3 if_out5" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:35.15-35.22" *)
  wire [3:0] \u24.u3.if_out5 ;
  (* hdlname = "u24 u3 u4 Y" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:226.22-226.23" *)
  wire [3:0] \u24.u3.u4.Y ;
  (* hdlname = "u24 u3 u5 Y" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:232.22-232.23" *)
  wire [3:0] \u24.u3.u5.Y ;
  (* hdlname = "u24 u3 u6 A" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:58.22-58.23" *)
  wire [3:0] \u24.u3.u6.A ;
  (* hdlname = "u24 u3 u6 if_out7" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:61.15-61.22" *)
  wire [3:0] \u24.u3.u6.if_out7 ;
  (* hdlname = "u24 u3 u6 if_out8" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:62.15-62.22" *)
  wire [3:0] \u24.u3.u6.if_out8 ;
  (* hdlname = "u24 u3 u6 u7 Y" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:238.22-238.23" *)
  wire [3:0] \u24.u3.u6.u7.Y ;
  (* hdlname = "u24 u3 u6 u8 Y" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:244.22-244.23" *)
  wire [3:0] \u24.u3.u6.u8.Y ;
  (* hdlname = "u24 u3 u6 u9 A" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:85.22-85.23" *)
  wire [3:0] \u24.u3.u6.u9.A ;
  (* hdlname = "u24 u3 u6 u9 if_out10" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:88.15-88.23" *)
  wire [3:0] \u24.u3.u6.u9.if_out10 ;
  (* hdlname = "u24 u3 u6 u9 if_out11" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:89.15-89.23" *)
  wire [3:0] \u24.u3.u6.u9.if_out11 ;
  (* hdlname = "u24 u3 u6 u9 u10 Y" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:250.22-250.23" *)
  wire [3:0] \u24.u3.u6.u9.u10.Y ;
  (* hdlname = "u24 u3 u6 u9 u11 Y" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:256.22-256.23" *)
  wire [3:0] \u24.u3.u6.u9.u11.Y ;
  (* hdlname = "u24 u3 u6 u9 u12 A" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:112.22-112.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.A ;
  (* hdlname = "u24 u3 u6 u9 u12 if_out13" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:115.15-115.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.if_out13 ;
  (* hdlname = "u24 u3 u6 u9 u12 if_out14" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:116.15-116.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.if_out14 ;
  (* hdlname = "u24 u3 u6 u9 u12 u13 Y" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:262.22-262.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.u13.Y ;
  (* hdlname = "u24 u3 u6 u9 u12 u14 Y" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:268.22-268.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.u14.Y ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 A" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:139.22-139.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.A ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 if_out16" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:142.15-142.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.if_out16 ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 if_out17" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:143.15-143.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.if_out17 ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 if_out18" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:144.16-144.24" *)
  (* unused_bits = "0 1 2" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.if_out18 ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 u16 Y" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:274.22-274.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.u16.Y ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 u17 Y" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:280.22-280.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.u17.Y ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 u18 A" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:166.22-166.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.u18.A ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 u18 Y" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:167.21-167.22" *)
  (* unused_bits = "0 1 2" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.u18.Y ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 u18 if_out19" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:169.15-169.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.u18.if_out19 ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 u18 if_out20" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:170.15-170.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.u18.if_out20 ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 u18 if_out21" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:171.16-171.24" *)
  (* unused_bits = "0" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.u18.if_out21 ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 u18 u19 Y" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:286.22-286.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.u18.u19.Y ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 u18 u20 Y" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:292.22-292.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.u18.u20.Y ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 u18 u21 A" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:193.22-193.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.u18.u21.A ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 u18 u21 Y" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:194.21-194.22" *)
  (* unused_bits = "0" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.u18.u21.Y ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 u18 u21 if_out22" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:196.15-196.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.u18.u21.if_out22 ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 u18 u21 if_out23" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:197.15-197.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.u18.u21.if_out23 ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 u18 u21 u22 Y" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:298.22-298.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.u18.u21.u22.Y ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 u18 u21 u23 Y" *)
  (* src = "/home/user/files/top_down/susskind_to_bin.v:304.22-304.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.u18.u21.u23.Y ;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h9248)
  ) Y_SB_LUT4_O (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) Y_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(A[2]),
    .I3(A[1]),
    .O(Y[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h808c)
  ) Y_SB_LUT4_O_2 (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0c00)
  ) Y_SB_LUT4_O_3 (
    .I0(1'h0),
    .I1(A[3]),
    .I2(A[2]),
    .I3(A[0]),
    .O(Y[3])
  );
  assign \u24.u3.A  = A;
  assign \u24.u2.Y  = 4'h0;
  assign \u24.u3.if_out4  = 4'h0;
  assign \u24.u3.if_out5  = 4'h1;
  assign \u24.u3.u4.Y  = 4'h0;
  assign \u24.u3.u5.Y  = 4'h1;
  assign \u24.u3.u6.A  = A;
  assign \u24.u1.Y  = 4'h0;
  assign \u24.u3.u6.if_out7  = 4'h4;
  assign \u24.u3.u6.if_out8  = 4'h0;
  assign out = Y;
  assign \u24.u3.u6.u7.Y  = 4'h4;
  assign \u24.u3.u6.u8.Y  = 4'h0;
  assign \u24.u3.u6.u9.A  = A;
  assign \u24.u3.u6.u9.if_out10  = 4'h3;
  assign \u24.u3.u6.u9.if_out11  = 4'h2;
  assign \u24.A  = A;
  assign \u24.u3.u6.u9.u10.Y  = 4'h3;
  assign \u24.u3.u6.u9.u11.Y  = 4'h2;
  assign \u24.u3.u6.u9.u12.A  = A;
  assign \u24.if_out2  = 4'h0;
  assign \u24.u3.u6.u9.u12.if_out13  = 4'h0;
  assign \u24.u3.u6.u9.u12.if_out14  = 4'h9;
  assign \u24.Y  = Y;
  assign \u24.u3.u6.u9.u12.u13.Y  = 4'h0;
  assign \u24.u3.u6.u9.u12.u14.Y  = 4'h9;
  assign \u24.u3.u6.u9.u12.u15.A  = A;
  assign \u24.if_out1  = 4'h0;
  assign \u24.u3.u6.u9.u12.u15.if_out16  = 4'h0;
  assign \u24.u3.u6.u9.u12.u15.if_out17  = 4'h8;
  assign \u24.u3.u6.u9.u12.u15.if_out18 [3] = 1'h0;
  assign \u24.u3.u6.u9.u12.u15.u16.Y  = 4'h0;
  assign \u24.u3.u6.u9.u12.u15.u17.Y  = 4'h8;
  assign \u24.u3.u6.u9.u12.u15.u18.A  = A;
  assign \u24.u3.u6.u9.u12.u15.u18.Y  = { 1'h0, \u24.u3.u6.u9.u12.u15.if_out18 [2:0] };
  assign \u24.u3.u6.u9.u12.u15.u18.if_out19  = 4'h5;
  assign \u24.u3.u6.u9.u12.u15.u18.if_out20  = 4'h0;
  assign \u24.u3.u6.u9.u12.u15.u18.if_out21 [3:1] = 3'h3;
  assign \u24.u3.u6.u9.u12.u15.u18.u19.Y  = 4'h5;
  assign \u24.u3.u6.u9.u12.u15.u18.u20.Y  = 4'h0;
  assign \u24.u3.u6.u9.u12.u15.u18.u21.A  = A;
  assign \u24.u3.u6.u9.u12.u15.u18.u21.Y  = { 3'h3, \u24.u3.u6.u9.u12.u15.u18.if_out21 [0] };
  assign \u24.u3.u6.u9.u12.u15.u18.u21.if_out22  = 4'h6;
  assign \u24.u3.u6.u9.u12.u15.u18.u21.if_out23  = 4'h7;
  assign \u24.u3.u6.u9.u12.u15.u18.u21.u22.Y  = 4'h6;
  assign \u24.u3.u6.u9.u12.u15.u18.u21.u23.Y  = 4'h7;
endmodule
