/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

(* hdlname = "susskind_to_bin" *)
(* top =  1  *)
(* src = "/home/user/files/if_(whole)/susskind_to_bin.v:3.1-179.10" *)
module susskind_to_bin(A, Y, unused);
  (* src = "/home/user/files/if_(whole)/susskind_to_bin.v:3.40-3.41" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "/home/user/files/if_(whole)/susskind_to_bin.v:3.59-3.60" *)
  output [3:0] Y;
  wire [3:0] Y;
  (* src = "/home/user/files/if_(whole)/susskind_to_bin.v:3.74-3.80" *)
  output unused;
  wire unused;
  (* src = "/home/user/files/if_(whole)/susskind_to_bin.v:7.15-7.20" *)
  wire [3:0] check;
  (* src = "/home/user/files/if_(whole)/susskind_to_bin.v:8.15-8.21" *)
  wire [3:0] check2;
  (* src = "/home/user/files/if_(whole)/susskind_to_bin.v:5.10-5.16" *)
  wire inited;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h9248)
  ) Y_SB_LUT4_O (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) Y_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(A[2]),
    .I3(A[1]),
    .O(Y[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h808c)
  ) Y_SB_LUT4_O_2 (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0c00)
  ) Y_SB_LUT4_O_3 (
    .I0(1'h0),
    .I1(A[3]),
    .I2(A[2]),
    .I3(A[0]),
    .O(Y[3])
  );
  assign check = 4'h4;
  assign check2 = 4'h9;
  assign inited = 1'h0;
  assign unused = 1'hx;
endmodule
