/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

(* hdlname = "gray_to_bin" *)
(* top =  1  *)
(* src = "/home/user/files/logic_gates/gray_to_bin.v:3.1-8.10" *)
module gray_to_bin(A, Y);
  (* src = "/home/user/files/logic_gates/gray_to_bin.v:3.36-3.37" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "/home/user/files/logic_gates/gray_to_bin.v:3.56-3.57" *)
  output [3:0] Y;
  wire [3:0] Y;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0ff0)
  ) Y_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(A[3]),
    .I3(A[2]),
    .O(Y[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0ff0)
  ) Y_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(A[1]),
    .I3(Y[2]),
    .O(Y[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0ff0)
  ) Y_SB_LUT4_O_2 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(A[0]),
    .I3(Y[1]),
    .O(Y[0])
  );
  assign Y[3] = A[3];
endmodule
