/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

(* hdlname = "susskind" *)
(* top =  1  *)
(* src = "/home/user/files/top_down/susskind.v:18.1-117.10" *)
module susskind(A, Y);
  (* src = "/home/user/files/top_down/susskind.v:19.20-19.21" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "/home/user/files/top_down/susskind.v:20.21-20.22" *)
  output [3:0] Y;
  wire [3:0] Y;
  (* unused_bits = "1" *)
  wire [1:0] if_out;
  (* src = "/home/user/files/top_down/susskind.v:24.15-24.22" *)
  (* unused_bits = "3" *)
  wire [3:0] if_out3;
  (* unused_bits = "1" *)
  wire [1:0] if_out5;
  (* hdlname = "u1 A" *)
  (* src = "/home/user/files/top_down/susskind.v:3.22-3.23" *)
  wire [3:0] \u1.A ;
  (* hdlname = "u1 B" *)
  (* src = "/home/user/files/top_down/susskind.v:4.21-4.22" *)
  wire [3:0] \u1.B ;
  (* hdlname = "u1 C" *)
  (* src = "/home/user/files/top_down/susskind.v:5.22-5.23" *)
  wire [3:0] \u1.C ;
  (* hdlname = "u1 D" *)
  (* src = "/home/user/files/top_down/susskind.v:6.22-6.23" *)
  wire [3:0] \u1.D ;
  (* hdlname = "u1 Y" *)
  (* src = "/home/user/files/top_down/susskind.v:7.19-7.20" *)
  (* unused_bits = "1" *)
  wire [3:0] \u1.Y ;
  (* hdlname = "u2 A" *)
  (* src = "/home/user/files/top_down/susskind.v:3.22-3.23" *)
  wire [3:0] \u2.A ;
  (* hdlname = "u2 B" *)
  (* src = "/home/user/files/top_down/susskind.v:4.21-4.22" *)
  wire [3:0] \u2.B ;
  (* hdlname = "u2 C" *)
  (* src = "/home/user/files/top_down/susskind.v:5.22-5.23" *)
  wire [3:0] \u2.C ;
  (* hdlname = "u2 D" *)
  (* src = "/home/user/files/top_down/susskind.v:6.22-6.23" *)
  wire [3:0] \u2.D ;
  (* hdlname = "u2 Y" *)
  (* src = "/home/user/files/top_down/susskind.v:7.19-7.20" *)
  wire [3:0] \u2.Y ;
  (* hdlname = "u3 A" *)
  (* src = "/home/user/files/top_down/susskind.v:3.22-3.23" *)
  wire [3:0] \u3.A ;
  (* hdlname = "u3 B" *)
  (* src = "/home/user/files/top_down/susskind.v:4.21-4.22" *)
  wire [3:0] \u3.B ;
  (* hdlname = "u3 C" *)
  (* src = "/home/user/files/top_down/susskind.v:5.22-5.23" *)
  wire [3:0] \u3.C ;
  (* hdlname = "u3 D" *)
  (* src = "/home/user/files/top_down/susskind.v:6.22-6.23" *)
  wire [3:0] \u3.D ;
  (* hdlname = "u3 Y" *)
  (* src = "/home/user/files/top_down/susskind.v:7.19-7.20" *)
  (* unused_bits = "3" *)
  wire [3:0] \u3.Y ;
  (* hdlname = "u4 A" *)
  (* src = "/home/user/files/top_down/susskind.v:3.22-3.23" *)
  wire [3:0] \u4.A ;
  (* hdlname = "u4 B" *)
  (* src = "/home/user/files/top_down/susskind.v:4.21-4.22" *)
  wire [3:0] \u4.B ;
  (* hdlname = "u4 C" *)
  (* src = "/home/user/files/top_down/susskind.v:5.22-5.23" *)
  wire [3:0] \u4.C ;
  (* hdlname = "u4 D" *)
  (* src = "/home/user/files/top_down/susskind.v:6.22-6.23" *)
  wire [3:0] \u4.D ;
  (* hdlname = "u4 Y" *)
  (* src = "/home/user/files/top_down/susskind.v:7.19-7.20" *)
  (* unused_bits = "0" *)
  wire [3:0] \u4.Y ;
  (* hdlname = "u5 A" *)
  (* src = "/home/user/files/top_down/susskind.v:3.22-3.23" *)
  wire [3:0] \u5.A ;
  (* hdlname = "u5 B" *)
  (* src = "/home/user/files/top_down/susskind.v:4.21-4.22" *)
  wire [3:0] \u5.B ;
  (* hdlname = "u5 C" *)
  (* src = "/home/user/files/top_down/susskind.v:5.22-5.23" *)
  wire [3:0] \u5.C ;
  (* hdlname = "u5 D" *)
  (* src = "/home/user/files/top_down/susskind.v:6.22-6.23" *)
  wire [3:0] \u5.D ;
  (* hdlname = "u5 Y" *)
  (* src = "/home/user/files/top_down/susskind.v:7.19-7.20" *)
  (* unused_bits = "1" *)
  wire [3:0] \u5.Y ;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h3330)
  ) Y_SB_LUT4_O (
    .I0(1'h0),
    .I1(A[3]),
    .I2(A[2]),
    .I3(A[1]),
    .O(Y[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h5152)
  ) Y_SB_LUT4_O_1 (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h4313)
  ) Y_SB_LUT4_O_2 (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h4642)
  ) Y_SB_LUT4_O_3 (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[3])
  );
  assign if_out[0] = 1'h1;
  assign if_out3[2:0] = 3'h4;
  assign if_out5[0] = 1'h1;
  assign \u1.A  = A;
  assign \u1.B  = 4'h0;
  assign \u1.C  = 4'h1;
  assign \u1.D  = 4'h3;
  assign \u1.Y  = { 2'h0, if_out[1], 1'h1 };
  assign \u2.A  = A;
  assign \u2.B  = 4'h2;
  assign \u2.C  = 4'h7;
  assign \u2.D  = 4'h6;
  assign \u2.Y  = 4'b011x;
  assign \u3.A  = A;
  assign \u3.B  = 4'h4;
  assign \u3.C  = 4'h4;
  assign \u3.D  = 4'hc;
  assign \u3.Y  = { if_out3[3], 3'h4 };
  assign \u4.A  = A;
  assign \u4.B  = 4'h6;
  assign \u4.C  = 4'he;
  assign \u4.D  = 4'hf;
  assign \u4.Y [3:1] = 3'h7;
  assign \u5.A  = A;
  assign \u5.B  = 4'h8;
  assign \u5.C  = 4'hb;
  assign \u5.D  = 4'h9;
  assign \u5.Y  = { 2'h2, if_out5[1], 1'h1 };
endmodule
