/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

(* hdlname = "XS3_Gray" *)
(* top =  1  *)
(* src = "/home/user/files/top_down/XS3_Gray.v:63.1-198.10" *)
module XS3_Gray(A, Y);
  (* src = "/home/user/files/top_down/XS3_Gray.v:64.20-64.21" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "/home/user/files/top_down/XS3_Gray.v:65.21-65.22" *)
  output [3:0] Y;
  wire [3:0] Y;
  wire [2:0] if_out;
  (* unused_bits = "1" *)
  wire [1:0] if_out2;
  wire [1:0] if_out3;
  (* unused_bits = "2" *)
  wire [2:0] if_out4;
  (* src = "/home/user/files/top_down/XS3_Gray.v:71.15-71.25" *)
  wire [3:0] switch_out;
  (* src = "/home/user/files/top_down/XS3_Gray.v:72.15-72.26" *)
  (* unused_bits = "2" *)
  wire [3:0] switch_out2;
  (* src = "/home/user/files/top_down/XS3_Gray.v:73.15-73.26" *)
  wire [3:0] switch_out3;
  (* hdlname = "u1 A" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:4.17-4.18" *)
  (* unused_bits = "0" *)
  wire \u1.A ;
  (* hdlname = "u1 B" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:5.21-5.22" *)
  wire [3:0] \u1.B ;
  (* hdlname = "u1 C" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:6.22-6.23" *)
  wire [3:0] \u1.C ;
  (* hdlname = "u1 G" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:9.22-9.23" *)
  wire [3:1] \u1.G ;
  (* hdlname = "u1 Y" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:8.22-8.23" *)
  wire [3:0] \u1.Y ;
  (* hdlname = "u10 A" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:16.17-16.18" *)
  (* unused_bits = "0" *)
  wire \u10.A ;
  (* hdlname = "u10 B" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:17.21-17.22" *)
  wire [3:0] \u10.B ;
  (* hdlname = "u10 C" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:18.22-18.23" *)
  wire [3:0] \u10.C ;
  (* hdlname = "u10 Y" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:19.21-19.22" *)
  wire [3:0] \u10.Y ;
  (* hdlname = "u11 A" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:16.17-16.18" *)
  (* unused_bits = "0" *)
  wire \u11.A ;
  (* hdlname = "u11 B" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:17.21-17.22" *)
  wire [3:0] \u11.B ;
  (* hdlname = "u11 C" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:18.22-18.23" *)
  wire [3:0] \u11.C ;
  (* hdlname = "u11 Y" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:19.21-19.22" *)
  wire [3:0] \u11.Y ;
  (* hdlname = "u12 Y" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:43.22-43.23" *)
  wire [7:0] \u12.Y ;
  (* hdlname = "u2 A" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:4.17-4.18" *)
  (* unused_bits = "0" *)
  wire \u2.A ;
  (* hdlname = "u2 B" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:5.21-5.22" *)
  wire [3:0] \u2.B ;
  (* hdlname = "u2 C" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:6.22-6.23" *)
  wire [3:0] \u2.C ;
  (* hdlname = "u2 G" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:9.22-9.23" *)
  wire [3:1] \u2.G ;
  (* hdlname = "u2 Y" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:8.22-8.23" *)
  wire [3:0] \u2.Y ;
  (* hdlname = "u3 A" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:4.17-4.18" *)
  (* unused_bits = "0" *)
  wire \u3.A ;
  (* hdlname = "u3 B" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:5.21-5.22" *)
  wire [3:0] \u3.B ;
  (* hdlname = "u3 C" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:6.22-6.23" *)
  wire [3:0] \u3.C ;
  (* hdlname = "u3 G" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:9.22-9.23" *)
  wire [3:1] \u3.G ;
  (* hdlname = "u3 Y" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:8.22-8.23" *)
  (* unused_bits = "1" *)
  wire [3:0] \u3.Y ;
  (* hdlname = "u4 A" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:4.17-4.18" *)
  (* unused_bits = "0" *)
  wire \u4.A ;
  (* hdlname = "u4 B" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:5.21-5.22" *)
  wire [3:0] \u4.B ;
  (* hdlname = "u4 C" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:6.22-6.23" *)
  wire [3:0] \u4.C ;
  (* hdlname = "u4 G" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:9.22-9.23" *)
  wire [3:1] \u4.G ;
  (* hdlname = "u4 Y" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:8.22-8.23" *)
  wire [3:0] \u4.Y ;
  (* hdlname = "u5 A" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:4.17-4.18" *)
  (* unused_bits = "0" *)
  wire \u5.A ;
  (* hdlname = "u5 B" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:5.21-5.22" *)
  wire [3:0] \u5.B ;
  (* hdlname = "u5 C" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:6.22-6.23" *)
  wire [3:0] \u5.C ;
  (* hdlname = "u5 G" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:9.22-9.23" *)
  wire [3:1] \u5.G ;
  (* hdlname = "u5 Y" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:8.22-8.23" *)
  (* unused_bits = "2" *)
  wire [3:0] \u5.Y ;
  (* hdlname = "u6 A" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:4.17-4.18" *)
  (* unused_bits = "0" *)
  wire \u6.A ;
  (* hdlname = "u6 B" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:5.21-5.22" *)
  wire [3:0] \u6.B ;
  (* hdlname = "u6 C" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:6.22-6.23" *)
  wire [3:0] \u6.C ;
  (* hdlname = "u6 G" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:9.22-9.23" *)
  wire [3:1] \u6.G ;
  (* hdlname = "u6 Y" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:8.22-8.23" *)
  (* unused_bits = "2" *)
  wire [3:0] \u6.Y ;
  (* hdlname = "u7 A" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:16.17-16.18" *)
  (* unused_bits = "0" *)
  wire \u7.A ;
  (* hdlname = "u7 B" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:17.21-17.22" *)
  wire [3:0] \u7.B ;
  (* hdlname = "u7 C" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:18.22-18.23" *)
  wire [3:0] \u7.C ;
  (* hdlname = "u7 Y" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:19.21-19.22" *)
  wire [3:0] \u7.Y ;
  (* hdlname = "u8 A" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:16.17-16.18" *)
  (* unused_bits = "0" *)
  wire \u8.A ;
  (* hdlname = "u8 B" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:17.21-17.22" *)
  wire [3:0] \u8.B ;
  (* hdlname = "u8 C" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:18.22-18.23" *)
  wire [3:0] \u8.C ;
  (* hdlname = "u8 Y" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:19.21-19.22" *)
  wire [3:0] \u8.Y ;
  (* hdlname = "u9 A" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:16.17-16.18" *)
  (* unused_bits = "0" *)
  wire \u9.A ;
  (* hdlname = "u9 B" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:17.21-17.22" *)
  wire [3:0] \u9.B ;
  (* hdlname = "u9 C" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:18.22-18.23" *)
  wire [3:0] \u9.C ;
  (* hdlname = "u9 Y" *)
  (* src = "/home/user/files/top_down/XS3_Gray.v:19.21-19.22" *)
  (* unused_bits = "2" *)
  wire [3:0] \u9.Y ;
  (* src = "/home/user/files/top_down/XS3_Gray.v:149.12-149.20" *)
  wire useless2;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h000f)
  ) Y_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(A[3]),
    .I3(Y[1]),
    .O(Y[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h300c)
  ) Y_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(A[3]),
    .I2(A[2]),
    .I3(A[1]),
    .O(Y[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h000f)
  ) Y_SB_LUT4_O_2 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(A[2]),
    .I3(A[1]),
    .O(Y[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0f00)
  ) Y_SB_LUT4_O_3 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(A[3]),
    .I3(A[1]),
    .O(Y[0])
  );
  assign if_out = 3'h2;
  assign if_out2 = { A[0], 1'h1 };
  assign if_out3 = 2'h1;
  assign if_out4 = { A[0], 2'h0 };
  assign switch_out = 4'h4;
  assign switch_out2 = { 1'h1, A[0], 2'h2 };
  assign switch_out3 = 4'h0;
  assign \u1.A  = A[0];
  assign \u1.B  = 4'h6;
  assign \u1.C  = 4'h2;
  assign \u1.G  = 3'h0;
  assign \u1.Y  = 4'h2;
  assign \u10.A  = A[0];
  assign \u10.B  = 4'h0;
  assign \u10.C  = 4'h1;
  assign \u10.Y  = 4'h0;
  assign \u11.A  = A[0];
  assign \u11.B  = 4'h0;
  assign \u11.C  = 4'h4;
  assign \u11.Y  = 4'h0;
  assign \u12.Y  = 8'h00;
  assign \u2.A  = A[0];
  assign \u2.B  = 4'h6;
  assign \u2.C  = 4'h2;
  assign \u2.G  = 3'h0;
  assign \u2.Y  = 4'h2;
  assign \u3.A  = A[0];
  assign \u3.B  = 4'h5;
  assign \u3.C  = 4'h7;
  assign \u3.G  = 3'h0;
  assign \u3.Y  = { 2'h1, A[0], 1'h1 };
  assign \u4.A  = A[0];
  assign \u4.B  = 4'hf;
  assign \u4.C  = 4'hd;
  assign \u4.G  = 3'h0;
  assign \u4.Y  = 4'hd;
  assign \u5.A  = A[0];
  assign \u5.B  = 4'h0;
  assign \u5.C  = 4'h4;
  assign \u5.G  = 3'h0;
  assign \u5.Y  = { 1'h0, A[0], 2'h0 };
  assign \u6.A  = A[0];
  assign \u6.B  = 4'h4;
  assign \u6.C  = 4'h2;
  assign \u6.G  = 3'h0;
  assign \u6.Y  = { 1'h0, A[0], 2'h0 };
  assign \u7.A  = A[0];
  assign \u7.B  = 4'h4;
  assign \u7.C  = 4'hc;
  assign \u7.Y  = 4'h4;
  assign \u8.A  = A[0];
  assign \u8.B  = 4'h4;
  assign \u8.C  = 4'hc;
  assign \u8.Y  = 4'h4;
  assign \u9.A  = A[0];
  assign \u9.B  = 4'he;
  assign \u9.C  = 4'ha;
  assign \u9.Y  = { 1'h1, A[0], 2'h2 };
  assign useless2 = 1'h0;
endmodule
