/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

(* hdlname = "OBrienII_to_bin" *)
(* top =  1  *)
(* src = "/home/user/files/top_down/OBrienII_to_bin.v:303.1-313.10" *)
module OBrienII_to_bin(A, Y);
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:304.20-304.21" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:305.22-305.23" *)
  output [3:0] Y;
  wire [3:0] Y;
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:307.15-307.18" *)
  wire [3:0] out;
  (* hdlname = "u24 A" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:4.22-4.23" *)
  wire [3:0] \u24.A ;
  (* hdlname = "u24 Y" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:5.21-5.22" *)
  wire [3:0] \u24.Y ;
  (* hdlname = "u24 case_out1" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:7.15-7.24" *)
  wire [3:0] \u24.case_out1 ;
  (* hdlname = "u24 case_out2" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:8.15-8.24" *)
  wire [3:0] \u24.case_out2 ;
  (* hdlname = "u24 u1 Y" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:208.22-208.23" *)
  wire [3:0] \u24.u1.Y ;
  (* hdlname = "u24 u2 Y" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:214.22-214.23" *)
  wire [3:0] \u24.u2.Y ;
  (* hdlname = "u24 u3 A" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:30.22-30.23" *)
  wire [3:0] \u24.u3.A ;
  (* hdlname = "u24 u3 case_out4" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:33.15-33.24" *)
  wire [3:0] \u24.u3.case_out4 ;
  (* hdlname = "u24 u3 case_out5" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:34.15-34.24" *)
  wire [3:0] \u24.u3.case_out5 ;
  (* hdlname = "u24 u3 u4 Y" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:220.22-220.23" *)
  wire [3:0] \u24.u3.u4.Y ;
  (* hdlname = "u24 u3 u5 Y" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:226.22-226.23" *)
  wire [3:0] \u24.u3.u5.Y ;
  (* hdlname = "u24 u3 u6 A" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:56.22-56.23" *)
  wire [3:0] \u24.u3.u6.A ;
  (* hdlname = "u24 u3 u6 case_out7" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:59.15-59.24" *)
  wire [3:0] \u24.u3.u6.case_out7 ;
  (* hdlname = "u24 u3 u6 case_out8" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:60.15-60.24" *)
  wire [3:0] \u24.u3.u6.case_out8 ;
  (* hdlname = "u24 u3 u6 u7 Y" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:232.22-232.23" *)
  wire [3:0] \u24.u3.u6.u7.Y ;
  (* hdlname = "u24 u3 u6 u8 Y" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:238.22-238.23" *)
  wire [3:0] \u24.u3.u6.u8.Y ;
  (* hdlname = "u24 u3 u6 u9 A" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:82.22-82.23" *)
  wire [3:0] \u24.u3.u6.u9.A ;
  (* hdlname = "u24 u3 u6 u9 case_out10" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:85.15-85.25" *)
  wire [3:0] \u24.u3.u6.u9.case_out10 ;
  (* hdlname = "u24 u3 u6 u9 case_out11" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:86.15-86.25" *)
  wire [3:0] \u24.u3.u6.u9.case_out11 ;
  (* hdlname = "u24 u3 u6 u9 u10 Y" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:244.22-244.23" *)
  wire [3:0] \u24.u3.u6.u9.u10.Y ;
  (* hdlname = "u24 u3 u6 u9 u11 Y" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:250.22-250.23" *)
  wire [3:0] \u24.u3.u6.u9.u11.Y ;
  (* hdlname = "u24 u3 u6 u9 u12 A" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:108.22-108.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.A ;
  (* hdlname = "u24 u3 u6 u9 u12 case_out13" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:111.15-111.25" *)
  wire [3:0] \u24.u3.u6.u9.u12.case_out13 ;
  (* hdlname = "u24 u3 u6 u9 u12 case_out14" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:112.15-112.25" *)
  wire [3:0] \u24.u3.u6.u9.u12.case_out14 ;
  (* hdlname = "u24 u3 u6 u9 u12 u13 Y" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:256.22-256.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.u13.Y ;
  (* hdlname = "u24 u3 u6 u9 u12 u14 Y" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:262.22-262.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.u14.Y ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 A" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:134.22-134.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.A ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 case_out16" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:137.15-137.25" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.case_out16 ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 case_out17" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:138.15-138.25" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.case_out17 ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 case_out18" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:139.16-139.26" *)
  (* unused_bits = "0 1 2" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.case_out18 ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 u16 Y" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:268.22-268.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.u16.Y ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 u17 Y" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:274.22-274.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.u17.Y ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 u18 A" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:160.22-160.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.u18.A ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 u18 Y" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:161.21-161.22" *)
  (* unused_bits = "0 1 2" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.u18.Y ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 u18 case_out19" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:163.15-163.25" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.u18.case_out19 ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 u18 case_out20" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:164.15-164.25" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.u18.case_out20 ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 u18 case_out21" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:165.16-165.26" *)
  (* unused_bits = "1 2" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.u18.case_out21 ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 u18 u19 Y" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:280.22-280.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.u18.u19.Y ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 u18 u20 Y" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:286.22-286.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.u18.u20.Y ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 u18 u21 A" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:186.22-186.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.u18.u21.A ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 u18 u21 Y" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:187.21-187.22" *)
  (* unused_bits = "1 2" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.u18.u21.Y ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 u18 u21 case_out22" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:189.15-189.25" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.u18.u21.case_out22 ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 u18 u21 case_out23" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:190.15-190.25" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.u18.u21.case_out23 ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 u18 u21 u22 Y" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:292.22-292.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.u18.u21.u22.Y ;
  (* hdlname = "u24 u3 u6 u9 u12 u15 u18 u21 u23 Y" *)
  (* src = "/home/user/files/top_down/OBrienII_to_bin.v:298.22-298.23" *)
  wire [3:0] \u24.u3.u6.u9.u12.u15.u18.u21.u23.Y ;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h00ac)
  ) Y_SB_LUT4_O (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h1268)
  ) Y_SB_LUT4_O_1 (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0c00)
  ) Y_SB_LUT4_O_2 (
    .I0(1'h0),
    .I1(A[3]),
    .I2(A[2]),
    .I3(A[0]),
    .O(Y[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h00f0)
  ) Y_SB_LUT4_O_3 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[1])
  );
  assign \u24.u3.A  = A;
  assign \u24.u2.Y  = 4'h0;
  assign \u24.u3.case_out4  = 4'h2;
  assign \u24.u3.case_out5  = 4'h1;
  assign \u24.u3.u4.Y  = 4'h2;
  assign \u24.u3.u5.Y  = 4'h1;
  assign \u24.u3.u6.A  = A;
  assign \u24.u1.Y  = 4'h0;
  assign \u24.u3.u6.case_out7  = 4'h4;
  assign \u24.u3.u6.case_out8  = 4'h0;
  assign out = Y;
  assign \u24.u3.u6.u7.Y  = 4'h4;
  assign \u24.u3.u6.u8.Y  = 4'h0;
  assign \u24.u3.u6.u9.A  = A;
  assign \u24.u3.u6.u9.case_out10  = 4'h3;
  assign \u24.u3.u6.u9.case_out11  = 4'h0;
  assign \u24.A  = A;
  assign \u24.u3.u6.u9.u10.Y  = 4'h3;
  assign \u24.u3.u6.u9.u11.Y  = 4'h0;
  assign \u24.u3.u6.u9.u12.A  = A;
  assign \u24.case_out2  = 4'h0;
  assign \u24.u3.u6.u9.u12.case_out13  = 4'h0;
  assign \u24.u3.u6.u9.u12.case_out14  = 4'h9;
  assign \u24.Y  = Y;
  assign \u24.u3.u6.u9.u12.u13.Y  = 4'h0;
  assign \u24.u3.u6.u9.u12.u14.Y  = 4'h9;
  assign \u24.u3.u6.u9.u12.u15.A  = A;
  assign \u24.case_out1  = 4'h0;
  assign \u24.u3.u6.u9.u12.u15.case_out16  = 4'h7;
  assign \u24.u3.u6.u9.u12.u15.case_out17  = 4'h8;
  assign \u24.u3.u6.u9.u12.u15.case_out18 [3] = 1'h0;
  assign \u24.u3.u6.u9.u12.u15.u16.Y  = 4'h7;
  assign \u24.u3.u6.u9.u12.u15.u17.Y  = 4'h8;
  assign \u24.u3.u6.u9.u12.u15.u18.A  = A;
  assign \u24.u3.u6.u9.u12.u15.u18.Y  = { 1'h0, \u24.u3.u6.u9.u12.u15.case_out18 [2:0] };
  assign \u24.u3.u6.u9.u12.u15.u18.case_out19  = 4'h5;
  assign \u24.u3.u6.u9.u12.u15.u18.case_out20  = 4'h0;
  assign { \u24.u3.u6.u9.u12.u15.u18.case_out21 [3:2], \u24.u3.u6.u9.u12.u15.u18.case_out21 [0] } = { 1'h0, \u24.u3.u6.u9.u12.u15.u18.case_out21 [1], 1'h0 };
  assign \u24.u3.u6.u9.u12.u15.u18.u19.Y  = 4'h5;
  assign \u24.u3.u6.u9.u12.u15.u18.u20.Y  = 4'h0;
  assign \u24.u3.u6.u9.u12.u15.u18.u21.A  = A;
  assign \u24.u3.u6.u9.u12.u15.u18.u21.Y  = { 1'h0, \u24.u3.u6.u9.u12.u15.u18.case_out21 [1], \u24.u3.u6.u9.u12.u15.u18.case_out21 [1], 1'h0 };
  assign \u24.u3.u6.u9.u12.u15.u18.u21.case_out22  = 4'h6;
  assign \u24.u3.u6.u9.u12.u15.u18.u21.case_out23  = 4'h0;
  assign \u24.u3.u6.u9.u12.u15.u18.u21.u22.Y  = 4'h6;
  assign \u24.u3.u6.u9.u12.u15.u18.u21.u23.Y  = 4'h0;
endmodule
