/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

(* hdlname = "BCD2421" *)
(* top =  1  *)
(* src = "/home/user/files/top_down/BCD2421.v:18.1-105.10" *)
module BCD2421(A, Y);
  (* src = "/home/user/files/top_down/BCD2421.v:19.20-19.21" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "/home/user/files/top_down/BCD2421.v:20.21-20.22" *)
  output [3:0] Y;
  wire [3:0] Y;
  (* src = "/home/user/files/top_down/BCD2421.v:22.16-22.26" *)
  wire [3:0] switch_out;
  (* src = "/home/user/files/top_down/BCD2421.v:23.16-23.27" *)
  wire [3:0] switch_out2;
  (* src = "/home/user/files/top_down/BCD2421.v:24.16-24.27" *)
  (* unused_bits = "2" *)
  wire [3:0] switch_out3;
  (* src = "/home/user/files/top_down/BCD2421.v:25.16-25.27" *)
  wire [3:0] switch_out4;
  (* src = "/home/user/files/top_down/BCD2421.v:26.16-26.27" *)
  wire [3:0] switch_out5;
  (* hdlname = "u1 A" *)
  (* src = "/home/user/files/top_down/BCD2421.v:4.17-4.18" *)
  wire \u1.A ;
  (* hdlname = "u1 B" *)
  (* src = "/home/user/files/top_down/BCD2421.v:5.21-5.22" *)
  wire [3:0] \u1.B ;
  (* hdlname = "u1 C" *)
  (* src = "/home/user/files/top_down/BCD2421.v:6.22-6.23" *)
  wire [3:0] \u1.C ;
  (* hdlname = "u1 Y" *)
  (* src = "/home/user/files/top_down/BCD2421.v:7.21-7.22" *)
  wire [3:0] \u1.Y ;
  (* hdlname = "u2 A" *)
  (* src = "/home/user/files/top_down/BCD2421.v:4.17-4.18" *)
  wire \u2.A ;
  (* hdlname = "u2 B" *)
  (* src = "/home/user/files/top_down/BCD2421.v:5.21-5.22" *)
  wire [3:0] \u2.B ;
  (* hdlname = "u2 C" *)
  (* src = "/home/user/files/top_down/BCD2421.v:6.22-6.23" *)
  wire [3:0] \u2.C ;
  (* hdlname = "u2 Y" *)
  (* src = "/home/user/files/top_down/BCD2421.v:7.21-7.22" *)
  wire [3:0] \u2.Y ;
  (* hdlname = "u3 A" *)
  (* src = "/home/user/files/top_down/BCD2421.v:4.17-4.18" *)
  wire \u3.A ;
  (* hdlname = "u3 B" *)
  (* src = "/home/user/files/top_down/BCD2421.v:5.21-5.22" *)
  wire [3:0] \u3.B ;
  (* hdlname = "u3 C" *)
  (* src = "/home/user/files/top_down/BCD2421.v:6.22-6.23" *)
  wire [3:0] \u3.C ;
  (* hdlname = "u3 Y" *)
  (* src = "/home/user/files/top_down/BCD2421.v:7.21-7.22" *)
  (* unused_bits = "2" *)
  wire [3:0] \u3.Y ;
  (* hdlname = "u4 A" *)
  (* src = "/home/user/files/top_down/BCD2421.v:4.17-4.18" *)
  wire \u4.A ;
  (* hdlname = "u4 B" *)
  (* src = "/home/user/files/top_down/BCD2421.v:5.21-5.22" *)
  wire [3:0] \u4.B ;
  (* hdlname = "u4 C" *)
  (* src = "/home/user/files/top_down/BCD2421.v:6.22-6.23" *)
  wire [3:0] \u4.C ;
  (* hdlname = "u4 Y" *)
  (* src = "/home/user/files/top_down/BCD2421.v:7.21-7.22" *)
  wire [3:0] \u4.Y ;
  (* hdlname = "u5 A" *)
  (* src = "/home/user/files/top_down/BCD2421.v:4.17-4.18" *)
  wire \u5.A ;
  (* hdlname = "u5 B" *)
  (* src = "/home/user/files/top_down/BCD2421.v:5.21-5.22" *)
  wire [3:0] \u5.B ;
  (* hdlname = "u5 C" *)
  (* src = "/home/user/files/top_down/BCD2421.v:6.22-6.23" *)
  wire [3:0] \u5.C ;
  (* hdlname = "u5 Y" *)
  (* src = "/home/user/files/top_down/BCD2421.v:7.21-7.22" *)
  wire [3:0] \u5.Y ;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h1612)
  ) Y_SB_LUT4_O (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h4246)
  ) Y_SB_LUT4_O_1 (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h4642)
  ) Y_SB_LUT4_O_2 (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h5700)
  ) Y_SB_LUT4_O_3 (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[0])
  );
  assign switch_out = { 3'h0, A[0] };
  assign switch_out2 = { 3'h1, A[0] };
  assign { switch_out3[3], switch_out3[1:0] } = { A[0], A[0], A[0] };
  assign switch_out4 = { 3'h6, A[0] };
  assign switch_out5 = { 3'h7, A[0] };
  assign \u1.A  = A[0];
  assign \u1.B  = 4'h0;
  assign \u1.C  = 4'h1;
  assign \u1.Y  = { 3'h0, A[0] };
  assign \u2.A  = A[0];
  assign \u2.B  = 4'h2;
  assign \u2.C  = 4'h3;
  assign \u2.Y  = { 3'h1, A[0] };
  assign \u3.A  = A[0];
  assign \u3.B  = 4'h4;
  assign \u3.C  = 4'hb;
  assign \u3.Y  = { A[0], switch_out3[2], A[0], A[0] };
  assign \u4.A  = A[0];
  assign \u4.B  = 4'hc;
  assign \u4.C  = 4'hd;
  assign \u4.Y  = { 3'h6, A[0] };
  assign \u5.A  = A[0];
  assign \u5.B  = 4'he;
  assign \u5.C  = 4'hf;
  assign \u5.Y  = { 3'h7, A[0] };
endmodule
