/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

(* hdlname = "OBrienII_to_bin" *)
(* top =  1  *)
(* src = "/home/user/files/logic_gates/OBrienII_to_bin.v:3.1-19.10" *)
module OBrienII_to_bin(A, Y);
  (* src = "/home/user/files/logic_gates/OBrienII_to_bin.v:3.35-3.36" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "/home/user/files/logic_gates/OBrienII_to_bin.v:3.50-3.51" *)
  output [3:0] Y;
  wire [3:0] Y;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h00ac)
  ) Y_SB_LUT4_O (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h1268)
  ) Y_SB_LUT4_O_1 (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0c00)
  ) Y_SB_LUT4_O_2 (
    .I0(1'h0),
    .I1(A[3]),
    .I2(A[2]),
    .I3(A[0]),
    .O(Y[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h00f0)
  ) Y_SB_LUT4_O_3 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[1])
  );
endmodule
