/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

(* hdlname = "XS3_Gray_to_bin" *)
(* top =  1  *)
(* src = "/home/user/files/logic_gates/XS3_Gray_to_bin.v:3.1-39.10" *)
module XS3_Gray_to_bin(A, Y);
  (* src = "/home/user/files/logic_gates/XS3_Gray_to_bin.v:3.35-3.36" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "/home/user/files/logic_gates/XS3_Gray_to_bin.v:3.50-3.51" *)
  output [3:0] Y;
  wire [3:0] Y;
  (* src = "/home/user/files/logic_gates/XS3_Gray_to_bin.v:5.10-5.15" *)
  wire and_1;
  (* src = "/home/user/files/logic_gates/XS3_Gray_to_bin.v:5.31-5.36" *)
  wire and_4;
  (* src = "/home/user/files/logic_gates/XS3_Gray_to_bin.v:6.10-6.14" *)
  wire or_1;
  (* src = "/home/user/files/logic_gates/XS3_Gray_to_bin.v:6.22-6.26" *)
  wire or_3;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h00c0)
  ) and_1_SB_LUT4_O (
    .I0(1'h0),
    .I1(A[3]),
    .I2(A[1]),
    .I3(A[0]),
    .O(and_1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) and_4_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(A[2]),
    .I3(A[0]),
    .O(and_4)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h880c)
  ) or_1_SB_LUT4_O (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(or_1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h8468)
  ) or_3_SB_LUT4_O (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(or_3)
  );
  assign Y = { and_1, or_1, and_4, or_3 };
endmodule
