/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

(* hdlname = "excess3_to_bin" *)
(* top =  1  *)
(* src = "/home/user/files/top_down/excess3_to_bin.v:253.1-263.10" *)
module excess3_to_bin(A, Y);
  (* src = "/home/user/files/top_down/excess3_to_bin.v:254.20-254.21" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "/home/user/files/top_down/excess3_to_bin.v:255.22-255.23" *)
  output [3:0] Y;
  wire [3:0] Y;
  (* src = "/home/user/files/top_down/excess3_to_bin.v:257.15-257.18" *)
  wire [3:0] out;
  (* hdlname = "u15 A" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:4.22-4.23" *)
  wire [3:0] \u15.A ;
  (* hdlname = "u15 Y" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:5.21-5.22" *)
  wire [3:0] \u15.Y ;
  (* hdlname = "u15 if2_out1" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:7.15-7.23" *)
  (* unused_bits = "0 1 2" *)
  wire [3:0] \u15.if2_out1 ;
  (* hdlname = "u15 u1 A" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:26.22-26.23" *)
  wire [3:0] \u15.u1.A ;
  (* hdlname = "u15 u1 Y" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:27.21-27.22" *)
  (* unused_bits = "0 1 2" *)
  wire [3:0] \u15.u1.Y ;
  (* hdlname = "u15 u1 if2_out3" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:29.15-29.23" *)
  wire [3:0] \u15.u1.if2_out3 ;
  (* hdlname = "u15 u1 if2_out4" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:30.15-30.23" *)
  (* unused_bits = "0 1 2" *)
  wire [3:0] \u15.u1.if2_out4 ;
  (* hdlname = "u15 u1 u3 A" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:70.23-70.24" *)
  wire [3:0] \u15.u1.u3.A ;
  (* hdlname = "u15 u1 u3 Y" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:71.21-71.22" *)
  wire [3:0] \u15.u1.u3.Y ;
  (* hdlname = "u15 u1 u3 if1_out1" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:73.15-73.23" *)
  wire [3:0] \u15.u1.u3.if1_out1 ;
  (* hdlname = "u15 u1 u3 if1_out2" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:74.15-74.23" *)
  wire [3:0] \u15.u1.u3.if1_out2 ;
  (* hdlname = "u15 u1 u3 u7 A" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:158.23-158.24" *)
  wire [3:0] \u15.u1.u3.u7.A ;
  (* hdlname = "u15 u1 u3 u7 Y" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:159.21-159.22" *)
  wire [3:0] \u15.u1.u3.u7.Y ;
  (* hdlname = "u15 u1 u3 u8 A" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:170.23-170.24" *)
  wire [3:0] \u15.u1.u3.u8.A ;
  (* hdlname = "u15 u1 u3 u8 Y" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:171.21-171.22" *)
  wire [3:0] \u15.u1.u3.u8.Y ;
  (* hdlname = "u15 u1 u4 A" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:92.23-92.24" *)
  wire [3:0] \u15.u1.u4.A ;
  (* hdlname = "u15 u1 u4 Y" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:93.21-93.22" *)
  (* unused_bits = "0 1 2" *)
  wire [3:0] \u15.u1.u4.Y ;
  (* hdlname = "u15 u1 u4 if1_out3" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:95.15-95.23" *)
  (* unused_bits = "0" *)
  wire [3:0] \u15.u1.u4.if1_out3 ;
  (* hdlname = "u15 u1 u4 if1_out4" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:96.15-96.23" *)
  (* unused_bits = "0 1" *)
  wire [3:0] \u15.u1.u4.if1_out4 ;
  (* hdlname = "u15 u1 u4 u10 A" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:194.23-194.24" *)
  wire [3:0] \u15.u1.u4.u10.A ;
  (* hdlname = "u15 u1 u4 u10 Y" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:195.21-195.22" *)
  (* unused_bits = "0 1" *)
  wire [3:0] \u15.u1.u4.u10.Y ;
  (* hdlname = "u15 u1 u4 u9 A" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:182.23-182.24" *)
  wire [3:0] \u15.u1.u4.u9.A ;
  (* hdlname = "u15 u1 u4 u9 Y" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:183.21-183.22" *)
  (* unused_bits = "0" *)
  wire [3:0] \u15.u1.u4.u9.Y ;
  (* hdlname = "u15 u2 A" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:48.23-48.24" *)
  wire [3:0] \u15.u2.A ;
  (* hdlname = "u15 u2 if2_out5" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:51.15-51.23" *)
  (* unused_bits = "0 1 2 3" *)
  wire [3:0] \u15.u2.if2_out5 ;
  (* hdlname = "u15 u2 if2_out6" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:52.15-52.23" *)
  (* unused_bits = "0 3" *)
  wire [3:0] \u15.u2.if2_out6 ;
  (* hdlname = "u15 u2 u5 A" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:114.23-114.24" *)
  wire [3:0] \u15.u2.u5.A ;
  (* hdlname = "u15 u2 u5 Y" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:115.21-115.22" *)
  (* unused_bits = "0 1 2 3" *)
  wire [3:0] \u15.u2.u5.Y ;
  (* hdlname = "u15 u2 u5 if1_out5" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:117.15-117.23" *)
  (* unused_bits = "0" *)
  wire [3:0] \u15.u2.u5.if1_out5 ;
  (* hdlname = "u15 u2 u5 if1_out6" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:118.15-118.23" *)
  (* unused_bits = "0 1 2" *)
  wire [3:0] \u15.u2.u5.if1_out6 ;
  (* hdlname = "u15 u2 u5 u11 A" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:206.23-206.24" *)
  wire [3:0] \u15.u2.u5.u11.A ;
  (* hdlname = "u15 u2 u5 u11 Y" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:207.21-207.22" *)
  (* unused_bits = "0" *)
  wire [3:0] \u15.u2.u5.u11.Y ;
  (* hdlname = "u15 u2 u5 u12 A" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:218.23-218.24" *)
  wire [3:0] \u15.u2.u5.u12.A ;
  (* hdlname = "u15 u2 u5 u12 Y" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:219.21-219.22" *)
  (* unused_bits = "0 1 2" *)
  wire [3:0] \u15.u2.u5.u12.Y ;
  (* hdlname = "u15 u2 u6 A" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:136.23-136.24" *)
  wire [3:0] \u15.u2.u6.A ;
  (* hdlname = "u15 u2 u6 Y" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:137.21-137.22" *)
  (* unused_bits = "0 3" *)
  wire [3:0] \u15.u2.u6.Y ;
  (* hdlname = "u15 u2 u6 if1_out7" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:139.15-139.23" *)
  (* unused_bits = "0 3" *)
  wire [3:0] \u15.u2.u6.if1_out7 ;
  (* hdlname = "u15 u2 u6 if1_out8" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:140.15-140.23" *)
  wire [3:0] \u15.u2.u6.if1_out8 ;
  (* hdlname = "u15 u2 u6 u13 A" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:230.23-230.24" *)
  wire [3:0] \u15.u2.u6.u13.A ;
  (* hdlname = "u15 u2 u6 u13 Y" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:231.21-231.22" *)
  (* unused_bits = "0 3" *)
  wire [3:0] \u15.u2.u6.u13.Y ;
  (* hdlname = "u15 u2 u6 u14 A" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:242.23-242.24" *)
  wire [3:0] \u15.u2.u6.u14.A ;
  (* hdlname = "u15 u2 u6 u14 Y" *)
  (* src = "/home/user/files/top_down/excess3_to_bin.v:243.21-243.22" *)
  wire [3:0] \u15.u2.u6.u14.Y ;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h4222)
  ) Y_SB_LUT4_O (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h006e)
  ) Y_SB_LUT4_O_1 (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h2008)
  ) Y_SB_LUT4_O_2 (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0660)
  ) Y_SB_LUT4_O_3 (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[1])
  );
  assign out = Y;
  assign \u15.A  = A;
  assign \u15.Y  = Y;
  assign \u15.if2_out1 [3] = 1'h0;
  assign \u15.u1.A  = A;
  assign \u15.u1.Y  = { 1'h0, \u15.if2_out1 [2:0] };
  assign \u15.u1.if2_out3  = 4'h0;
  assign \u15.u1.if2_out4 [3] = 1'h0;
  assign \u15.u1.u3.A  = A;
  assign \u15.u1.u3.Y  = 4'h0;
  assign \u15.u1.u3.if1_out1  = 4'h0;
  assign \u15.u1.u3.if1_out2  = 4'h0;
  assign \u15.u1.u3.u7.A  = A;
  assign \u15.u1.u3.u7.Y  = 4'h0;
  assign \u15.u1.u3.u8.A  = A;
  assign \u15.u1.u3.u8.Y  = 4'h0;
  assign \u15.u1.u4.A  = A;
  assign \u15.u1.u4.Y  = { 1'h0, \u15.u1.if2_out4 [2:0] };
  assign \u15.u1.u4.if1_out3  = { 2'h0, A[0], \u15.u1.if2_out4 [0] };
  assign \u15.u1.u4.if1_out4  = { 1'h0, A[0], \u15.u1.if2_out4 [0], \u15.u1.if2_out4 [0] };
  assign \u15.u1.u4.u10.A  = A;
  assign \u15.u1.u4.u10.Y  = { 1'h0, A[0], \u15.u1.if2_out4 [0], \u15.u1.if2_out4 [0] };
  assign \u15.u1.u4.u9.A  = A;
  assign \u15.u1.u4.u9.Y  = { 2'h0, A[0], \u15.u1.if2_out4 [0] };
  assign \u15.u2.A  = A;
  assign { \u15.u2.if2_out5 [3], \u15.u2.if2_out5 [1:0] } = \u15.u1.if2_out4 [2:0];
  assign \u15.u2.if2_out6 [3:1] = { \u15.u2.if2_out6 [0], 2'h0 };
  assign \u15.u2.u5.A  = A;
  assign \u15.u2.u5.Y  = { \u15.u1.if2_out4 [2], \u15.u2.if2_out5 [2], \u15.u1.if2_out4 [1:0] };
  assign \u15.u2.u5.if1_out5  = { 2'h1, A[0], \u15.u1.if2_out4 [0] };
  assign \u15.u2.u5.if1_out6  = { A[0], \u15.u1.if2_out4 [0], \u15.u1.if2_out4 [0], \u15.u1.if2_out4 [0] };
  assign \u15.u2.u5.u11.A  = A;
  assign \u15.u2.u5.u11.Y  = { 2'h1, A[0], \u15.u1.if2_out4 [0] };
  assign \u15.u2.u5.u12.A  = A;
  assign \u15.u2.u5.u12.Y  = { A[0], \u15.u1.if2_out4 [0], \u15.u1.if2_out4 [0], \u15.u1.if2_out4 [0] };
  assign \u15.u2.u6.A  = A;
  assign \u15.u2.u6.Y  = { \u15.u2.if2_out6 [0], 2'h0, \u15.u2.if2_out6 [0] };
  assign \u15.u2.u6.if1_out7  = { \u15.u1.if2_out4 [0], 2'h0, \u15.u1.if2_out4 [0] };
  assign \u15.u2.u6.if1_out8  = 4'h0;
  assign \u15.u2.u6.u13.A  = A;
  assign \u15.u2.u6.u13.Y  = { \u15.u1.if2_out4 [0], 2'h0, \u15.u1.if2_out4 [0] };
  assign \u15.u2.u6.u14.A  = A;
  assign \u15.u2.u6.u14.Y  = 4'h0;
endmodule
