/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

(* hdlname = "XS3_Gray" *)
(* top =  1  *)
(* src = "/home/user/files/logic_gates/XS3_Gray.v:3.1-45.10" *)
module XS3_Gray(A, Y);
  (* src = "/home/user/files/logic_gates/XS3_Gray.v:3.28-3.29" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "/home/user/files/logic_gates/XS3_Gray.v:3.43-3.44" *)
  output [3:0] Y;
  wire [3:0] Y;
  (* src = "/home/user/files/logic_gates/XS3_Gray.v:6.16-6.20" *)
  wire or_2;
  (* src = "/home/user/files/logic_gates/XS3_Gray.v:6.22-6.26" *)
  wire or_3;
  (* src = "/home/user/files/logic_gates/XS3_Gray.v:6.28-6.32" *)
  wire or_4;
  (* src = "/home/user/files/logic_gates/XS3_Gray.v:6.34-6.38" *)
  wire or_5;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h4642)
  ) or_2_SB_LUT4_O (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(or_2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h5556)
  ) or_3_SB_LUT4_O (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(or_3)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h4313)
  ) or_4_SB_LUT4_O (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(or_4)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0f00)
  ) or_5_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(A[3]),
    .I3(A[1]),
    .O(or_5)
  );
  assign Y = { or_2, or_3, or_4, or_5 };
endmodule
