/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

(* hdlname = "gray_code" *)
(* top =  1  *)
(* src = "/home/user/files/top_down/gray_code.v:11.1-31.10" *)
module gray_code(A, Y);
  (* src = "/home/user/files/top_down/gray_code.v:12.21-12.22" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "/home/user/files/top_down/gray_code.v:13.22-13.23" *)
  output [3:0] Y;
  wire [3:0] Y;
  (* hdlname = "u1 A" *)
  (* src = "/home/user/files/top_down/gray_code.v:4.17-4.18" *)
  wire \u1.A ;
  (* hdlname = "u1 B" *)
  (* src = "/home/user/files/top_down/gray_code.v:5.17-5.18" *)
  wire \u1.B ;
  (* hdlname = "u1 Y" *)
  (* src = "/home/user/files/top_down/gray_code.v:6.17-6.18" *)
  wire \u1.Y ;
  (* hdlname = "u2 A" *)
  (* src = "/home/user/files/top_down/gray_code.v:4.17-4.18" *)
  wire \u2.A ;
  (* hdlname = "u2 B" *)
  (* src = "/home/user/files/top_down/gray_code.v:5.17-5.18" *)
  wire \u2.B ;
  (* hdlname = "u2 Y" *)
  (* src = "/home/user/files/top_down/gray_code.v:6.17-6.18" *)
  wire \u2.Y ;
  (* hdlname = "u3 A" *)
  (* src = "/home/user/files/top_down/gray_code.v:4.17-4.18" *)
  wire \u3.A ;
  (* hdlname = "u3 B" *)
  (* src = "/home/user/files/top_down/gray_code.v:5.17-5.18" *)
  wire \u3.B ;
  (* hdlname = "u3 Y" *)
  (* src = "/home/user/files/top_down/gray_code.v:6.17-6.18" *)
  wire \u3.Y ;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0ff0)
  ) \u1.Y_SB_LUT4_O  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(A[3]),
    .I3(A[2]),
    .O(\u1.Y )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0ff0)
  ) \u2.Y_SB_LUT4_O  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(A[2]),
    .I3(A[1]),
    .O(\u2.Y )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0ff0)
  ) \u3.Y_SB_LUT4_O  (
    .I0(1'h0),
    .I1(1'h0),
    .I2(A[1]),
    .I3(A[0]),
    .O(\u3.Y )
  );
  assign Y = { A[3], \u1.Y , \u2.Y , \u3.Y  };
  assign \u1.A  = A[3];
  assign \u1.B  = A[2];
  assign \u2.A  = A[2];
  assign \u2.B  = A[1];
  assign \u3.A  = A[1];
  assign \u3.B  = A[0];
endmodule
