/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

(* hdlname = "OBrienII" *)
(* top =  1  *)
(* src = "/home/user/files/if_(whole)/OBrienII.v:4.1-124.10" *)
module OBrienII(A, Y);
  (* src = "/home/user/files/if_(whole)/OBrienII.v:4.33-4.34" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "/home/user/files/if_(whole)/OBrienII.v:4.52-4.53" *)
  output [3:0] Y;
  wire [3:0] Y;
  (* src = "/home/user/files/if_(whole)/OBrienII.v:104.103-104.104" *)
  wire B;
  (* src = "/home/user/files/if_(whole)/OBrienII.v:6.10-6.16" *)
  wire inited;
  (* src = "/home/user/files/if_(whole)/OBrienII.v:8.10-8.14" *)
  wire test;
  (* src = "/home/user/files/if_(whole)/OBrienII.v:9.10-9.15" *)
  wire test2;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hc6e2)
  ) Y_SB_LUT4_O (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'ha303)
  ) Y_SB_LUT4_O_1 (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hd1f2)
  ) Y_SB_LUT4_O_2 (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/user/yosys_mod/share/ice40/cells_map.v:26.33-27.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h94c4)
  ) Y_SB_LUT4_O_3 (
    .I0(A[3]),
    .I1(A[2]),
    .I2(A[1]),
    .I3(A[0]),
    .O(Y[2])
  );
  assign B = 1'hx;
  assign inited = 1'h1;
  assign test = 1'hx;
  assign test2 = 1'hz;
endmodule
